tasks:
  - name: Install Foundry
    before: |
      docker-compose -f "./data/Data/modules/octomori-sheet/docker-compose.yml" pull
      docker-compose -f "./data/Data/modules/octomori-sheet/docker-compose.yml" up -d
checkoutLocation: "./data/Data/modules/octomori-sheet"
workspaceLocation: "/workspace"

additionalRepositories:
  - url: https://github.com/megastruktur/foundryvtt-octomori.git
    checkoutLocation: "./data/Data/systems/octomori"
